using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PB.Shared.Enum
{
    public enum Languages
    {
        Afrikaans=1,
        Albanian,
        Arabic,
        Azerbaijani,
        Bengali,
        Bulgarian,
        Catalan,
        Chinese_CHN,
        Chinese_HKG,
        Chinese_TAI,
        Croatian,
        Czech,
        Danish,
        Dutch,
        English,
        English_UK,
        English_US,
        Estonian,
        Filipino,
        Finnish,
        French,
        German,
        Greek,
        Gujarati,
        Hausa,
        Hebrew,
        Hindi,
        Hungarian,
        Indonesian,
        Irish,
        Italian,
        Japanese,
        Kannada,
        Kazakh,
        Korean,
        Lao,
        Latvian,
        Lithuanian,
        Macedonian,
        Malay,
        Malayalam,
        Marathi,
        Norwegian,
        Persian,
        Polish,
        Portuguese_BR,
        Portuguese_POR,
        Punjabi,
        Romanian,
        Russian,
        Serbian,
        Slovak,
        Slovenian,
        Spanish,
        Spanish_ARG,
        Spanish_SPA,
        Spanish_MEX,
        Swahili,
        Swedish,
        Tamil,
        Telugu,
        Thai,
        Turkish,
        Ukrainian,
        Urdu,
        Uzbek,
        Vietnamese,
        Zulu
    }
}
