//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PB.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResponseMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResponseMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PB.Shared.Resources.ResponseMessage", typeof(ResponseMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already logged in the app.
        /// </summary>
        public static string AlreadyLoggedIn {
            get {
                return ResourceManager.GetString("AlreadyLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your approval is pending.
        /// </summary>
        public static string ApprovalPending {
            get {
                return ResourceManager.GetString("ApprovalPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch name already exist.
        /// </summary>
        public static string BranchExist {
            get {
                return ResourceManager.GetString("BranchExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Cannot Delete Home Branch.
        /// </summary>
        public static string DefaultBranchDeletion {
            get {
                return ResourceManager.GetString("DefaultBranchDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to any branch.
        /// </summary>
        public static string DontHaveBranch {
            get {
                return ResourceManager.GetString("DontHaveBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Exist.
        /// </summary>
        public static string EmailExist {
            get {
                return ResourceManager.GetString("EmailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address not found.
        /// </summary>
        public static string EmailNotFound {
            get {
                return ResourceManager.GetString("EmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify your email addess.
        /// </summary>
        public static string EmailNotVerified {
            get {
                return ResourceManager.GetString("EmailNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong!!.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops...
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your current password.
        /// </summary>
        public static string InvalidCurrentPassword {
            get {
                return ResourceManager.GetString("InvalidCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid OTP.
        /// </summary>
        public static string InvalidOTP {
            get {
                return ResourceManager.GetString("InvalidOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your password.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your user name.
        /// </summary>
        public static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not active.
        /// </summary>
        public static string LoginInactive {
            get {
                return ResourceManager.GetString("LoginInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number Exist.
        /// </summary>
        public static string MobileExist {
            get {
                return ResourceManager.GetString("MobileExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add File name.
        /// </summary>
        public static string NoFileName {
            get {
                return ResourceManager.GetString("NoFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload an image.
        /// </summary>
        public static string NoImage {
            get {
                return ResourceManager.GetString("NoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP has been sent to your email address.
        /// </summary>
        public static string OTPSentToEmail {
            get {
                return ResourceManager.GetString("OTPSentToEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User priority should be greater than.
        /// </summary>
        public static string PriorityShouldbeGreaterthan {
            get {
                return ResourceManager.GetString("PriorityShouldbeGreaterthan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You donot have permission to access this application.
        /// </summary>
        public static string ProhibittedApp {
            get {
                return ResourceManager.GetString("ProhibittedApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;v done!!.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You dont have access to this branch.
        /// </summary>
        public static string UnPermittedBranch {
            get {
                return ResourceManager.GetString("UnPermittedBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete this user type beause users already exist in this user group.
        /// </summary>
        public static string UserExistOnUserType {
            get {
                return ResourceManager.GetString("UserExistOnUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name already exist.
        /// </summary>
        public static string UserNameExist {
            get {
                return ResourceManager.GetString("UserNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User type already exist.
        /// </summary>
        public static string UserTypeExist {
            get {
                return ResourceManager.GetString("UserTypeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User type not found or you do not have access permission.
        /// </summary>
        public static string UserTypeNotFound {
            get {
                return ResourceManager.GetString("UserTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goto your inbox and enter otp for verification.
        /// </summary>
        public static string VerifyOTP {
            get {
                return ResourceManager.GetString("VerifyOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify your account.
        /// </summary>
        public static string VerifyOTPTitle {
            get {
                return ResourceManager.GetString("VerifyOTPTitle", resourceCulture);
            }
        }
    }
}
